#!/usr/bin/env bash

IMAGE_NAME="${IMAGE_NAME:-rhscl/httpd-24-rhel7}"

THISDIR=$(dirname ${BASH_SOURCE[0]})
. ${THISDIR}/utils.sh
test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"

function create_container() {
    local name="$1" ; shift
    local image="${1-$IMAGE_NAME}" ; shift
    cidfile="$CIDFILE_DIR/$name"
    # create container with a cidfile in a directory for cleanup
    docker run ${DOCKER_ARGS:-} --cidfile $cidfile -d $image || return 1
    echo docker run ${DOCKER_ARGS:-} --cidfile $cidfile -d $image
    echo "Created container $(cat $cidfile)"
}

function update_overall {
    res="$1"
    if [ "$res" != 0 ]; then
        overall="$res"
    fi
}

function get_cid() {
  local id="$1" ; shift || return 1
  echo $(cat "$CIDFILE_DIR/$id")
}

function get_container_ip() {
    local id="$1" ; shift
    docker inspect --format='{{.NetworkSettings.IPAddress}}' $(get_cid "$id")
}

function rm_container {
    local name="$1"
    local cid="`get_cid $name`"
    docker kill "$cid"
    docker rm "$cid"
    rm -f "$CIDFILE_DIR/$name"
}

function run {
    cmd="$1"
    expected_res="${2:-0}"
    msg="${3:-Running command '$cmd'}"
    run_command "$cmd" "$expected_res" "$msg"
    res=$?
    update_overall $res
    return $res
}

tmpdir=`mktemp -d`
pushd $tmpdir > /dev/null || exit 1

CIDFILE_DIR=cid_files
mkdir "$CIDFILE_DIR"

overall=0

run "docker inspect $IMAGE_NAME >/dev/null || docker pull $IMAGE_NAME" 0

# Check default page
run "create_container test_default_page"
sleep 2
run "curl $(get_container_ip 'test_default_page') > output"
run "fgrep -e 'Test Page for the Apache HTTP Server on Red Hat Enterprise Linux' output"
rm_container test_default_page

# Check the HTTP_LOG_TO_VOLUME env variable
run "ls -d /var/log/httpd24-logs || mkdir /var/log/httpd24-logs" 0 'Create log directory'
run "chcon -Rvt svirt_sandbox_file_t /var/log/httpd24-logs" 0 'Change SELinux context on the log dir'
DOCKER_ARGS='-e HTTPD_LOG_TO_VOLUME=1 -v /var/log/httpd24-logs:/var/log/httpd24'
run "create_container test_log_dir"
DOCKER_ARGS=
sleep 2
run "curl $(get_container_ip 'test_log_dir') > /dev/null"
ls /var/log/httpd24-logs > output
run "grep -e '^access_log$' output" 0 "Checking that file access_log exists"
run "grep -e '^error_log$' output" 0 "Checking that file error_log exists"
run "grep -e '^ssl_access_log$' output" 0 "Checking that file ssl_access_log exists"
run "grep -e '^ssl_error_log$' output" 0 "Checking that file ssl_error_log exists"
run "grep -e '^ssl_request_log$' output" 0 "Checking that file ssl_request_log exists"
rm_container test_log_dir

# Test that docker volume for DocumentRoot works
run "ls -d /var/www/html/ || mkdir -p /var/www/html/" 0 'Create document root'
run "echo hello > /var/www/html/index.html"
run "chcon -Rvt svirt_sandbox_file_t /var/www/" 0 'Change SELinux context on the document root'
DOCKER_ARGS='-v /var/www:/opt/rh/httpd24/root/var/www'
run "create_container test_doc_root"
DOCKER_ARGS=
sleep 2
run "curl $(get_container_ip 'test_doc_root') > output"
run "grep -e '^hello$' output"
rm_container test_doc_root

# Test s2i use case
# Since we built the candidate image locally, we don't want S2I attempt to pull
# it from Docker hub
s2i_args="--force-pull=false"
run "s2i usage ${s2i_args} ${IMAGE_NAME}" 0 "Testing 's2i usage'"
run "s2i build ${s2i_args} file://${test_dir}/sample-test-app ${IMAGE_NAME} ${IMAGE_NAME}-testapp" 0 "Testing 's2i build'"
DOCKER_ARGS='-u 1000'
create_container testing-app-s2i ${IMAGE_NAME}-testapp
DOCKER_ARGS=
sleep 5
run "curl $(get_container_ip 'testing-app-s2i'):8080 > output_s2i"
run "fgrep -e 'This is a sample s2i application with static content.' output_s2i"
# 0 "Checking page served by s2i feature"
sleep 2
rm_container "testing-app-s2i"

popd > /dev/null
rm -Rf "$tmpdir"

exit "$overall"
