FROM registry.redhat.io/rhel10/httpd-24

# This image supports the Source-to-Image
# In order to support the Source-to-Image framework, there are some interesting
# scripts inside the builder image, that can be run in a Dockerfile directly as well:
# * The `/usr/libexec/s2i/assemble` script inside the image is run in order
#   to produce a new image with the application artifacts.
#   The script takes sources of a given application and places them into
#   appropriate directories inside the image.
# * The `/usr/libexec/s2i/run` script executes the application and is set as
#   a default command in the resulting container image.
# Add application sources
ADD . /tmp/src

# Assemble script installs the dependencies
RUN /usr/libexec/s2i/assemble

# Run script uses standard ways to run the application
CMD /usr/libexec/s2i/run
